spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/advisor_information_scraping
    username: ais_dev
    password: ais_dev_pass

  jpa:
    generate-ddl: true
    show-sql: false

    hibernate:
      ddl-auto: none

selenium:
  chrome-driver-location: C:/Program Files (x86)/Selenium/chromedriver.exe
  chrome-location: C:/Program Files (x86)/Google/Chrome/Application/chrome.exe
  firefox-driver-location: C:/Program Files (x86)/Selenium/geckodriver.exe
